[package]
name = "typed_fixedbitset"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

[dependencies]
fixedbitset = "0.1"
serde = { version = "1", optional = true }
